theme: jekyll-theme-hacker
title: Biolisp
description: Hacking biological data science
avatar: <img width="339" alt="biolisp_logo" src="https://user-images.githubusercontent.com/9893806/29801564-1ecd1802-8c25-11e7-9ab8-0ec875970542.png">
